// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg72oBZ3iDyVMmVCfALvV_NQhNi1klalI',
    appId: '1:891508661382:web:69b4ec40e7bb43ef714507',
    messagingSenderId: '891508661382',
    projectId: 'flutter-agent-doctor',
    authDomain: 'flutter-agent-doctor.firebaseapp.com',
    storageBucket: 'flutter-agent-doctor.firebasestorage.app',
    measurementId: 'G-75J4S77YHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9nGCmUzgwskd_L_dG6k8HB0voB1L3mLU',
    appId: '1:891508661382:android:fe2c80d49a48cf73714507',
    messagingSenderId: '891508661382',
    projectId: 'flutter-agent-doctor',
    storageBucket: 'flutter-agent-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELUNVyBTpvHt8CJWPTgDkQsoEgFiirAU',
    appId: '1:891508661382:ios:12edf83a5b9c6f5f714507',
    messagingSenderId: '891508661382',
    projectId: 'flutter-agent-doctor',
    storageBucket: 'flutter-agent-doctor.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAELUNVyBTpvHt8CJWPTgDkQsoEgFiirAU',
    appId: '1:891508661382:ios:12edf83a5b9c6f5f714507',
    messagingSenderId: '891508661382',
    projectId: 'flutter-agent-doctor',
    storageBucket: 'flutter-agent-doctor.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg72oBZ3iDyVMmVCfALvV_NQhNi1klalI',
    appId: '1:891508661382:web:fb3010eb663e022f714507',
    messagingSenderId: '891508661382',
    projectId: 'flutter-agent-doctor',
    authDomain: 'flutter-agent-doctor.firebaseapp.com',
    storageBucket: 'flutter-agent-doctor.firebasestorage.app',
    measurementId: 'G-W6G19W34Q6',
  );
}
